# Generated by Django 4.2.5 on 2023-09-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('kardon', 'kardon'), ('atlantic', 'atlantic'), ('university', 'university'), ('james_s_white', 'james_s_white'), ('j_h', 'j_h'), ('nineteen_forty', 'nineteen_forty'), ('conwell', 'conwell'), ('edge', 'edge'), ('morgan_hall', 'morgan_hall'), ('oxford_village', 'oxford_village'), ('thirteen', 'thirteen'), ('temple_towers', 'temple_towers'), ('beech', 'beech')], max_length=20)),
                ('health_score', models.IntegerField()),
            ],
        ),
    ]
